# Generated by Django 5.1.6 on 2025-02-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='sneakers')),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='product',
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
